### ISSUE TITLE
mask rcnn: "Tensor Reshape error", did anyone meet this problem

### ISSUE THREAD

**Issue by qmzpg** [CharlesShang/FastMaskRCNN#103]
**I get the following problem when trainning coco data, I use anaconda2(python2.7), i7 GTX960**

2017-07-11 15:19:54.866372: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.05GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
iter 0: image-id:0007932, time:4.556(sec), regular_loss: 0.202816, total-loss 2.1600(0.0296, 0.5545, 0.003872, 0.8789, 0.6931), instances: 5, batch:(17|89, 5|69, 5|5)
Traceback (most recent call last):
  File "./train/train.py", line 223, in <module>
    train()
  File "./train/train.py", line 219, in train
    coord.join(threads)
  File "/home/administrator/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/administrator/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/queue_runner_impl.py", line 238, in _run
    enqueue_callable()
  File "/home/administrator/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1193, in _single_operation_run
    target_list_as_strings, status, None)
  File "/home/administrator/anaconda2/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/home/administrator/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 1 values, but the requested shape has 0
	 [[Node: Reshape_1 = Reshape[T=DT_INT32, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](Cast_4/_567, Reshape_1/shape)]]
	 [[Node: ReverseV2/_599 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_277_ReverseV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

**Comment by insikk** [comment]
Are you trying to run this code with Tensorflow 1.2? You should run it with TF1.1 See this #88

**Comment by qmzpg** [comment]
Thank insikk .
