### ISSUE TITLE
ImportError: /usr/local/lib/python2.7/dist-packages/cv2.so: undefined symbol

### ISSUE THREAD

**Issue by lirui111** [CharlesShang/FastMaskRCNN#111]
I'm just a beginner.when I run the train.py,there are some problems.How can I deal with the problem?
Traceback (most recent call last):
  File "train/train.py", line 21, in <module>
    import libs.nets.pyramid_network as pyramid_network
  File "train/../libs/nets/pyramid_network.py", line 10, in <module>
    from libs.layers import anchor_encoder
  File "train/../libs/layers/__init__.py", line 9, in <module>
    from .wrapper import anchor_decoder
  File "train/../libs/layers/wrapper.py", line 12, in <module>
    from . import mask
  File "train/../libs/layers/mask.py", line 7, in <module>
    import cv2
ImportError: /usr/local/lib/python2.7/dist-packages/cv2.so: undefined symbol: _ZN2cv11arrowedLineERNS_3MatENS_6Point_IiEES3_RKNS_7Scalar_IdEEiiid

**Comment by chenzhuo1005** [comment]
Run:
pip3 install --upgrade opencv-python
should fix it

**Comment by Mageshpoondi** [comment]
Thank you...I was trying to install OpenCV3.3 on Ubuntu 14.04 with Python 3.4.3 and faced the error 

.virtualenvs/cv2/lib/python3.4/site-packages/cv2.so: undefined symbol: _ZTIN2cv3dnn19experimental_dnn_v15LayerE

and doing 
pip3 install --upgrade opencv-python
completed the import of cv2.  Thank you.

**Comment by ivder** [comment]
For addition, if you want to upgrade to specific version just run this command for example
`pip3 install --upgrade opencv-python==3.3.1.11`
