### ISSUE TITLE
Invalid argument: Could not parse example input

### ISSUE THREAD

**Issue by santisy** [CharlesShang/FastMaskRCNN#12]
When step of training reaches about `1140`, there is a parse problem which seems to be related to `.tfrecord`file. 

Error type: `UnicodeDecodeError: 'utf8' codec can't decode byte 0xaf in position 40: invalid start byte`

The corresponding tfrecord file is `./data/coco/record/coco_train2014_00000-of-00040.tfrecord`

Do you encounter the same problem? @CharlesShang 
```
W tensorflow/core/kernels/queue_base.cc:294] _0_input_producer: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
  File "test/resnet50_test.py", line 137, in <module>
    run_metadata=run_metadata)
  File "/home/santis/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/santis/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/santis/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/santis/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1022, in _do_call
    return fn(*args)
  File "/home/santis/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1004, in _run_fn
    status, run_metadata)
  File "/home/santis/anaconda2/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/home/santis/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 465, in raise_exception_on_not_ok_status
    compat.as_text(pywrap_tensorflow.TF_Message(status)),
  File "/home/santis/anaconda2/lib/python2.7/site-packages/tensorflow/python/util/compat.py", line 84, in as_text
    return bytes_or_text.decode(encoding)
  File "/home/santis/anaconda2/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xaf in position 40: invalid start byte

```

**Comment by tweedmorris** [comment]
Hi @santisy. I got the same error, seems (ultimately) caused by a large input. Updating to tensorflow 1.1.0rc1 and installing the patched version of the python protobuf library (https://www.tensorflow.org/versions/r0.12/get_started/os_setup#protobuf_library_related_issues) seems to fix the issue.

**Comment by santisy** [comment]
Thank you @tweedmorris . It does seem to solve this problem.

**Comment by maxenceliu** [comment]
after i upgrade tf to 1.1.0rc2 and upgrade protobuf...
it shows:

2017-04-20 18:11:49.563798: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: indices[0] = 3842514323579820651 is not in [0, 4)

2017-04-20 18:11:49.584574: W tensorflow/core/kernels/queue_base.cc:294] _0_input_producer: Skipping cancelled enqueue attempt with queue not closed

**Comment by maxenceliu** [comment]
and after I switch tf1.0 to tf1.1, it becomes normal.... so many magic problems...
