### ISSUE TITLE
Multi-Thread Control

### ISSUE THREAD

**Issue by eveningdong** [CharlesShang/FastMaskRCNN#131]
So when I run code on COCO Detection 2014, with all setting default, I met following error. 

Hardware & Software:
Ubuntu 16.04 LTS
tensorflow 1.2.1
Nvidia GTX Titan X  * 2
Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz

`
Traceback (most recent call last):
  File "train/train.py", line 339, in <module>
    train()
  File "train/train.py", line 335, in train
    coord.join(threads)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 238, in _run
    enqueue_callable()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1063, in _single_operation_run
    target_list_as_strings, status, None)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 1 values, but the requested shape has 0
	 [[Node: Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](DecodeRaw_1/_555, Reshape/shape)]]
	 [[Node: ReverseV2/_599 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_277_ReverseV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
`
I tried on single GPU and two GPUs on same machine, same issue.

**Comment by catalinolaru1** [comment]
I have the same issue. Does anyone know how to fix this?

**Comment by eveningdong** [comment]
@catalinolaru1 I fixed that. It seems that tf.1.0.1 is not perfect compatible with tf.1.2.x, at least for multi-thread control.
