### ISSUE TITLE
nvalidArgumentError: Input to reshape is a tensor with 1 values, but the requested shape has 0

### ISSUE THREAD

**Issue by WKChung1028** [CharlesShang/FastMaskRCNN#151]
I am using Virtual Environment and CPU and tensorflow 1.3 to run the train.py.
Before literation 115, everything is fine. but after that, the literation stopped. Then, I enter the same command again, the error occurred as shown as below.  Hope to get help .

SyntaxError: invalid syntax
(my_project) ubuntu@ubuntu-IDP1:~/Documents/WK/FastMaskRCNN$ python train/train.py
Traceback (most recent call last):
  File "train/train.py", line 28, in <module>
    from libs.datasets import download_and_convert_coco
  File "train/../libs/datasets/download_and_convert_coco.py", line 232
    ors_impl.InvalidArgumentError: Input to reshape is a tensor with 1 values, but the requested shape has 0

**Comment by LifeBeyondExpectations** [comment]
I also got same problem

**Comment by w-tingting** [comment]
I have the same problem,could you tell me how do you solve it?

**Comment by WKChung1028** [comment]
I have no idea to solve it . i hope somebody can help , now i am trying on GPU

**Comment by hanskrupakar** [comment]
Solved in #113
