### ISSUE TITLE
Is it possible to run on a CPU?

### ISSUE THREAD

**Issue by jasonwei20** [CharlesShang/FastMaskRCNN#155]
Has anyone has been able to get the code up and running on a CPU with no CUDA?

**Comment by successren** [comment]
It  can not run on computers without CUDA, unless you modified the code
===================================================================
python setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 55, in <module>
    CUDA = locate_cuda()
  File "setup.py", line 43, in locate_cuda
    raise EnvironmentError('The nvcc binary could not be '
OSError: The nvcc binary could not be located in your $PATH. Either add it to your path, or set $CUDAHOME
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by WKChung1028** [comment]
refer to #62
