### ISSUE TITLE
error when download_and_convert_coco

### ISSUE THREAD

**Issue by maxenceliu** [CharlesShang/FastMaskRCNN#16]
Traceback (most recent call last):
  File "download_and_convert_data.py", line 9, in <module>
    from libs.datasets import download_and_convert_coco
  File "/home/liuming/python_projects/FastMaskRCNN/libs/datasets/download_and_convert_coco.py", line 17, in <module>
    from libs.datasets.pycocotools.coco import COCO
  File "/home/liuming/python_projects/FastMaskRCNN/libs/datasets/pycocotools/coco.py", line 55, in <module>
    from libs.datasets.pycocotools import mask as maskUtils # change importing
  File "/home/liuming/python_projects/FastMaskRCNN/libs/datasets/pycocotools/mask.py", line 3, in <module>
    import libs.datasets.pycocotools._mask as _mask
ImportError: No module named _mask

**Comment by xilaili** [comment]
You need to make it first.

**Comment by maxenceliu** [comment]
Yes... I found that... Thx any way~ @xilaili

**Comment by HanYuanyuaner** [comment]
@xilaili I have make it, but still has this problem
