### ISSUE TITLE
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa. What's woring with it. Thanks for help

### ISSUE THREAD

**Issue by miraclewxl** [CharlesShang/FastMaskRCNN#169]
Traceback (most recent call last):
  File "__init__.pxd", line 987, in numpy.import_array
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/wxl/00063DAF000FECC3/FastMaskRCNN-master/train/train.py", line 28, in <module>
    from libs.datasets import download_and_convert_coco
  File "/media/wxl/00063DAF000FECC3/FastMaskRCNN-master/train/../libs/datasets/download_and_convert_coco.py", line 17, in <module>
    from libs.datasets.pycocotools.coco import COCO
  File "/media/wxl/00063DAF000FECC3/FastMaskRCNN-master/train/../libs/datasets/pycocotools/coco.py", line 55, in <module>
    from libs.datasets.pycocotools import mask as maskUtils # change importing
  File "/media/wxl/00063DAF000FECC3/FastMaskRCNN-master/train/../libs/datasets/pycocotools/mask.py", line 3, in <module>
    import libs.datasets.pycocotools._mask as _mask
  File "_mask.pyx", line 23, in init libs.datasets.pycocotools._mask
  File "__init__.pxd", line 989, in numpy.import_array
ImportError: numpy.core.multiarray failed to import

I reinstall numpy. But the problem is still exist. I donn't know how the fix it. Thanks for your answers

**Comment by miraclewxl** [comment]
I upgrade numpy. The numpy is 1.12.1

**Comment by Sharathnasa** [comment]
https://github.com/matterport/Mask_RCNN
Look at this repo.. They have implemented it. All the best..

**Comment by nevakanezzar** [comment]
Also encountered this issue (in another context). What worked for me is tracking down a duplicate copy of numpy sitting within /usr/lib/python3/dist-packages and deleting it.

**Comment by pawamoy** [comment]
I fixed this by reinstalling all the dependencies (including numpy) in a dedicated virtualenv.
```
virtualenv -p python3.5 py35
. py35/bin/activate
pip install ...
```
