### ISSUE TITLE
python download_and_convert_data.py 出现错误怎么解决呀

### ISSUE THREAD

**Issue by pbbpby231456** [CharlesShang/FastMaskRCNN#182]
Traceback (most recent call last):
  File "download_and_convert_data.py", line 39, in <module>
    tf.app.run()
  File "/mnt/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "download_and_convert_data.py", line 33, in main
    download_and_convert_coco.run(FLAGS.dataset_dir, FLAGS.dataset_split_name)
  File "/mnt/FastMaskRCNN-master/libs/datasets/download_and_convert_coco.py", line 460, in run
    dataset_split_name)
  File "/mnt/FastMaskRCNN-master/libs/datasets/download_and_convert_coco.py", line 296, in _add_to_tfrecord
    gt_boxes, masks, mask = _get_coco_masks(coco, img_id, height, width, img_name)
  File "/mnt/FastMaskRCNN-master/libs/datasets/download_and_convert_coco.py", line 209, in _get_coco_masks
    cat_id = _cat_id_to_real_id(ann['category_id'])
  File "/mnt/FastMaskRCNN-master/libs/datasets/download_and_convert_coco.py", line 88, in _cat_id_to_real_id
    return cat_id_to_real_id[readId]
KeyError: 121

**Comment by chongkong** [comment]
Little suggestion: 
1. It would be helpful for other readers if you use the English rather than Chinese at the title
2. stack trace is better readable with ` ``` ` formatting (you can use the language `console`)

**Comment by EMCL** [comment]
```
creating index...
index created!
Traceback (most recent call last):
  File "download_and_convert_data.py", line 39, in <module>
    tf.app.run()
  File "/home/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "download_and_convert_data.py", line 33, in main
    download_and_convert_coco.run(FLAGS.dataset_dir, FLAGS.dataset_split_name)
  File "/home/work/FastMaskRCNN/libs/datasets/download_and_convert_coco.py", line 457, in run
    dataset_split_name)
  File "/home/work/FastMaskRCNN/libs/datasets/download_and_convert_coco.py", line 245, in _add_to_tfrecord
    cats = `coco.loadCats(coco.getCatIds())`
  File "/home/work/FastMaskRCNN/libs/datasets/pycocotools/coco.py", line 165, in getCatIds
    cats = self.dataset['''categories''']
KeyError: 'categories'

```
