### ISSUE TITLE
KeyError: 'categories'

### ISSUE THREAD

**Issue by EMCL** [CharlesShang/FastMaskRCNN#197]
lanka@ubuntu:~/work/FastMaskRCNN$ python download_and_convert_data.py
loading annotations into memory...
Done (t=5.22s)
creating index...
index created!
Traceback (most recent call last):
  File "download_and_convert_data.py", line 39, in <module>
    tf.app.run()
  File "/home/lanka/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "download_and_convert_data.py", line 33, in main
    download_and_convert_coco.run(FLAGS.dataset_dir, FLAGS.dataset_split_name)
  File "/home/lanka/work/FastMaskRCNN/libs/datasets/download_and_convert_coco.py", line 457, in run
    dataset_split_name)
  File "/home/lanka/work/FastMaskRCNN/libs/datasets/download_and_convert_coco.py", line 245, in _add_to_tfrecord
    cats = coco.loadCats(coco.getCatIds())
  File "/home/lanka/work/FastMaskRCNN/libs/datasets/pycocotools/coco.py", line 165, in getCatIds
    cats = self.dataset['''categories''']
KeyError: 'categories'

**Comment by Yuli555** [comment]
How did you solve the problem?

**Comment by satish1901** [comment]
any solution to this.?

**Comment by diliprc96** [comment]
Any update on this??
