### ISSUE TITLE
What my issue when I run train.py

### ISSUE THREAD

**Issue by macqueen09** [CharlesShang/FastMaskRCNN#49]
# whats my issue is:
* 1 my 'make' in lib was:
`python setup.py build_ext --inplace   

running build_ext
skipping 'boxes/bbox.c' Cython extension (up-to-date)
skipping 'boxes/cython_anchor.c' Cython extension (up-to-date)
skipping 'boxes/cython_bbox_transform.c' Cython extension (up-to-date)
skipping 'boxes/nms.c' Cython extension (up-to-date)
skipping 'nms/cpu_nms.c' Cython extension (up-to-date)
skipping 'nms/gpu_nms.cpp' Cython extension (up-to-date)
rm -rf build
sh make.sh
make[1]: Entering directory `/home/king/Documents/macqueen/FastMaskRCNN/libs/datasets/pycocotools'
python setup.py build_ext --inplace
running build_ext
rm -rf build
make[1]: Leaving directory `/home/king/Documents/macqueen/FastMaskRCNN/libs/datasets/pycocotools'
/home/king/Documents/macqueen/FastMaskRCNN/libs
`
** I don't know whether it is right 

* and when i run the train.py I get the error:

`Traceback (most recent call last):

  File "train/train.py", line 187, in <module>
    train()
  File "train/train.py", line 100, in train
    is_training=True)
  File "train/../libs/datasets/dataset_factory.py", line 18, in get_dataset
    image, gt_boxes, gt_masks = coco_preprocess.preprocess_image(image, gt_boxes, gt_masks, is_training)
  File "train/../libs/preprocessings/coco_v1.py", line 23, in preprocess_image
    return preprocess_for_training(image, gt_boxes, gt_masks)
  File "train/../libs/preprocessings/coco_v1.py", line 38, in preprocess_for_training
    lambda: (image, gt_boxes, gt_masks))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1710, in cond
    orig_res, res_t = context_t.BuildCondBranch(fn1)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1613, in BuildCondBranch
    r = fn()
  File "train/../libs/preprocessings/coco_v1.py", line 35, in <lambda>
    lambda: (preprocess_utils.flip_image(image),
  File "train/../libs/preprocessings/utils.py", line 170, in flip_image
    return tf.reverse(image, axis=[1])
TypeError: reverse() got an unexpected keyword argument 'axis'
`

**Comment by amirbar** [comment]
looks like you're on a wrong TF version, which version are you on?

**Comment by zhanglijian** [comment]
I have meet the similarity problem, my TF version is 1.1.0,

**Comment by amirbar** [comment]
see:
https://www.tensorflow.org/api_docs/python/tf/reverse

**Comment by gavinzhang1995** [comment]
i have same problem.did you  solved it?
