### ISSUE TITLE
heloo evryone !! when I  python train.py , TF version:1.0.1  meet this issue : 

### ISSUE THREAD

**Issue by zhanglijian** [CharlesShang/FastMaskRCNN#52]
(tensorflow)he_su@ljz-Ubuntu:~/work/FastMaskRCNN/train$ python train.py
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "train.py", line 222, in <module>
    train()
  File "train.py", line 114, in train
    is_training=True)
  File "../libs/datasets/dataset_factory.py", line 16, in get_dataset
    image, ih, iw, gt_boxes, gt_masks, num_instances, img_id = coco.read(tfrecords)
  File "../libs/datasets/coco.py", line 98, in read
    tfrecords_filename, num_epochs=100)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/input.py", line 211, in string_input_producer
    raise ValueError(not_null_err)
ValueError: string_input_producer requires a non-null input tensor

**Comment by amirbar** [comment]
Hi,

Did you download the coco data & placed it in the right folder?
Do you have tfrecords created in './data/coco/records'?

**Comment by zhanglijian** [comment]
@amirbar ,Hi
I did download the coco data and placed them like that:
![_001](https://cloud.githubusercontent.com/assets/12655032/26289944/9e8c7034-3ed6-11e7-9710-6f0abefe8e5f.png)

I did have tfrecords created in './data/coco/records' only 33 .tfrecord files

**Comment by zhanglijian** [comment]
@amirbar ,Hi ,thanks for your message
when I 'python  download_and_convert_data.py '  ,like this ,there are lots of images 
'None Annotations data/coco/train2014/....'

**Comment by mattdingmeng** [comment]
@zhanglijian I have exactly the same error with you. Did you figure it out? I also have 33 files in the record folder.
@amirbar I did what you said. Could you have other solutions?

**Comment by tjussh** [comment]
@mattdingmeng I have the same error, and  I also have 33 files in the './data/coco/records' folder. I don't exactly know if this will affect the operation behind. 
I see in file FastMaskRCNN/unit_test/data_test.py, line 30:
coco.read('./data/coco/records/coco_trainval2014_00000-of-**00048**.tfrecord')
It should be 48 files in './data/coco/records'. 
I checked the MD5 of my zip files, and all files are right.  
Someone has any idea?

**Comment by lileiNPU** [comment]
@zhanglijian 
Hi, have you solved this problem?

**Comment by blitu12345** [comment]
@zhanglijian  @mattdingmeng  @lileiNPU 
As mentioned [here](https://github.com/CharlesShang/FastMaskRCNN/blob/master/libs/datasets/download_and_convert_coco.py#L187) Actually this is not an error as some images are annotated and it is only printing them out [here](https://github.com/CharlesShang/FastMaskRCNN/blob/master/libs/datasets/download_and_convert_coco.py#L220). This is according to my understanding please correct me if im wrong! Thanks.

**Comment by zhanglijian** [comment]
@lileiNPU  I have no idea about that,do you have solved this problem??

**Comment by lileiNPU** [comment]
I have solved the error. Modify the code in 'dataset_factory.py'. 

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import glob
from libs.datasets import coco
import libs.preprocessings.coco_v1 as coco_preprocess

def get_dataset(dataset_name, split_name, dataset_dir, 
        im_batch=1, is_training=False, file_pattern=None, reader=None):
    """"""
    if file_pattern is None:
        #file_pattern = dataset_name + '_' + split_name + '*.tfrecord' 
        file_pattern = '/home/daxika/FastMaskRCNN-master/data/coco/' + '*' 
    temp = file_pattern
    tfrecords = glob.glob(temp)
    # tfrecords = glob.glob(dataset_dir + '/records/' + file_pattern)
    image, ih, iw, gt_boxes, gt_masks, num_instances, img_id = coco.read(tfrecords)

    image, gt_boxes, gt_masks = coco_preprocess.preprocess_image(image, gt_boxes, gt_masks, is_training)

    return image, ih, iw, gt_boxes, gt_masks, num_instances, img_id

**Comment by 404noahfound** [comment]
This issue is caused by the working directory problem.
In line 16 of ./libs/datasets/dataset_factory.py
`tfrecords = glob.glob(dataset_dir + '/records/' + file_pattern)`,
add one preceding '../'
`tfrecords = glob.glob('../'+dataset_dir + '/records/' + file_pattern)`
Hope this helps.

**Comment by 404noahfound** [comment]
Actually the same issue persist in following execution. Better solution is to run train.py in the project root directory.
`python train/train.py`

**Comment by Llcm** [comment]
@404noahfound thanks for your answer
