### ISSUE TITLE
hen I make './libs/', there is a problem as follows. 

### ISSUE THREAD

**Issue by shenkeng853** [CharlesShang/FastMaskRCNN#55]
''''
Traceback (most recent call last):
  File "setup.py", line 55, in <module>
    CUDA = locate_cuda()
  File "setup.py", line 50, in locate_cuda
    for k, v in cudaconfig.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
''''
My cuda version is cuda 7.0 
Is that my fault of cuda?

**Comment by zhanglijian** [comment]
it should be cuda8.0, cudnn7.5

**Comment by lymrty** [comment]
no, are you sure you installed dict module?

**Comment by TJCVRS** [comment]
@shenkeng853 I believe you are using Python 3 to compile it. You should change the iteritems into items, which should work correctly.

**Comment by zhuwenzhen** [comment]
@TJCVRS I run into the same problem, your solution works!

**Comment by forlovess** [comment]
python2
