### ISSUE TITLE
When you execute the download_and_convert_data.py, some of the images are not found and how do you resolve them? The methods listed are tried and cannot be solved 

### ISSUE THREAD

**Issue by xingbowei** [CharlesShang/FastMaskRCNN#73]
>> Converting image 12901/82783 shard 5
>> Converting image 12951/82783 shard 5
>> Converting image 13001/82783 shard 5
>> Converting image 13051/82783 shard 5
>> Converting image 13101/82783 shard 5
None Annotations data/coco/train2014/COCO_train2014_000000544188.jpg
>> Converting image 13151/82783 shard 5
>> Converting image 13201/82783 shard 5
None Annotations data/coco/train2014/COCO_train2014_000000413222.jpg
None Annotations data/coco/train2014/COCO_train2014_000000413232.jpg
>> Converting image 13251/82783 shard 5
>> Converting image 13301/82783 shard 5
>> Converting image 13351/82783 shard 5
>> Converting image 13401/82783 shard 5
>> Converting image 13451/82783 shard 5
>> Converting image 13501/82783 shard 5
None Annotations data/coco/train2014/COCO_train2014_000000282586.jpg
None Annotations data/coco/train2014/COCO_train2014_000000020490.jpg
>> Converting image 13551/82783 shard 5
>> Converting image 13601/82783 shard 5
>> Converting image 13651/82783 shard 5
>> Converting image 13701/82783 shard 5
>> Converting image 13751/82783 shard 5

**Comment by skyline1006** [comment]
I also meet this problem,and it creats 33 tfrecord files in records.I have no ides ,and i don't konw weather it will  affect the following experiment....

**Comment by CodeIsWorld** [comment]
i also meet this problem and when the program run to "Converting image 23851/82783 shard 9"
it exit
print error 

"Traceback (most recent call last):
  File "download_and_convert_data.py", line 36, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "download_and_convert_data.py", line 30, in main
    download_and_convert_coco.run(FLAGS.dataset_dir, FLAGS.dataset_split_name)
  File "/media/rxh/d81049f1-91e4-4ed3-88e8-bba6eb163601/home/zz/Desktop/FastMaskRCNN-master/libs/datasets/download_and_convert_coco.py", line 460, in run
    dataset_split_name)
  File "/media/rxh/d81049f1-91e4-4ed3-88e8-bba6eb163601/home/zz/Desktop/FastMaskRCNN-master/libs/datasets/download_and_convert_coco.py", line 306, in _add_to_tfrecord
    img = img.astype(np.uint8)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 528, in __getattr__
    raise AttributeError(name)
AttributeError: __trunc__
"

**Comment by xingbowei** [comment]
I have not encountered this problem ,the explanation in this link address(https://stackoverflow.com/questions/27280211/pil-attribute-error) may be helpful to you.

**Comment by wldeephi** [comment]
@CodeIsWorld , I encountered the same error, have you solved it?
