### ISSUE TITLE
The path problem and resnet_v1_50.ckpt are all right, and I don't know why ？

### ISSUE THREAD

**Issue by xingbowei** [CharlesShang/FastMaskRCNN#75]
dels/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
Checking your params ./data/pretrained_models/resnet_v1_50.ckpt
Traceback (most recent call last):
  File "train.py", line 222, in <module>
    train()
  File "train.py", line 166, in train
    restore(sess)
  File "train.py", line 97, in restore
    restorer.restore(sess, checkpoint_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1439, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
	 [[Node: save_1/RestoreV2_66 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_66/tensor_names, save_1/RestoreV2_66/shape_and_slices)]]
	 [[Node: save_1/RestoreV2_34/_471 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_1267_save_1/RestoreV2_34", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'save_1/RestoreV2_66', defined at:
  File "train.py", line 222, in <module>
    train()
  File "train.py", line 166, in train
    restore(sess)
  File "train.py", line 96, in restore
    restorer = tf.train.Saver(vars_to_restore)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1051, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1081, in build
    restore_sequentially=self._restore_sequentially)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 675, in build
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 402, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 242, in restore_op
    [spec.tensor.dtype])[0])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 668, in restore_v2
    dtypes=dtypes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./data/pretrained_models/resnet_v1_50.ckpt: Not found: ./data/pretrained_models
	 [[Node: save_1/RestoreV2_66 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_66/tensor_names, save_1/RestoreV2_66/shape_and_slices)]]
	 [[Node: save_1/RestoreV2_34/_471 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_1267_save_1/RestoreV2_34", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

**Comment by lileiNPU** [comment]
out of memory

**Comment by xingbowei** [comment]
where can you see that there is insufficient memory?

**Comment by PavlosMelissinos** [comment]
There is no ./data/pretrained_models directory so it can't load the model.

**Comment by xingbowei** [comment]
This problem has just been solved by changing the relative path to an absolute path

**Comment by HuangBo-Terraloupe** [comment]
Hello xingbowei,

Can you please share the code you changed?  It will be really helpful.
Did you only make changes in the config_v1?

best

**Comment by xingbowei** [comment]
Modified here：
tf.app.flags.DEFINE_string(
    'pretrained_model', '/home/xbw/FastMaskRCNN-master/data/pretrained_models/resnet_v1_50.ckpt',
    'Path to pretrained model')

**Comment by xingbowei** [comment]
In config_v1. Py
