### ISSUE TITLE
Issue in layers.mask

### ISSUE THREAD

**Issue by nitish11** [CharlesShang/FastMaskRCNN#83]
While running the training, after running for some iterations, I am getting a runtime error.  Please find below the screenshot of the error. 

```
iter 52: image-id:0000075, time:19.824(sec), regular_loss: 0.202733, total-loss 0.7085(0.0099, 0.5361, 0.000000, 0.1625, 0.0000), instances: 1, batch:(12|72, 0|64, 0|0)
------------------------------------------------------------
**-- np.shape(mask_targets) : <type 'numpy.ndarray'> (65, 28, 28, 3)
-- np.shape((labels[i])   : <type 'numpy.float32'> 3.0
-- np.shape(cropped)      : <type 'numpy.ndarray'> (28, 28)**
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/script_ops.py", line 82, in __call__
    ret = func(*args)
  File "train/../libs/layers/mask.py", line 84, in encode
    mask_inside_weights[i, :, :, int(labels[i])] = 1
IndexError: index 3 is out of bounds for axis 3 with size 3
2017-06-13 15:14:06.920219: W tensorflow/core/framework/op_kernel.cc:1152] Internal: Failed to run py callback pyfunc_14: see error log.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/script_ops.py", line 82, in __call__
    ret = func(*args)
  File "train/../libs/layers/roi.py", line 85, in encode
    rois[keep_inds, 0:4], gt_boxes[gt_assignment[keep_inds], :4], labels[keep_inds], num_classes)
  File "train/../libs/layers/roi.py", line 151, in _compute_targets
    bbox_targets[ind, start:end] = targets[ind, 0:4]
ValueError: could not broadcast input array from shape (4) into shape (0)
```

It is obvious from the log that it is because of variable "labels[i]", which is coming as 3 and it should be less than 3.  Have you faced similar issue?

**Comment by Iftimie** [comment]
Hi!
Did you solve the issue? I am facing the same problem. I have a batch size of 1. Are you training on the COCO dataset? I am training on VOC and I was wondering if I did something wrong while adapting the script.

**Comment by nitish11** [comment]
@Iftimie : I couldn't solve the problem. The issue is still there, but for a quick work-round, refer [line](https://github.com/CharlesShang/FastMaskRCNN/blob/master/libs/layers/mask.py#L77) , 

add you can add there, 

```
if labels[i] > np.shape(mask_targets)[3]:
    labels[i] =np.shape(mask_targets)[3] 
```
