### ISSUE TITLE
No module named 'nms'

### ISSUE THREAD

**Issue by zhuwenzhen** [CharlesShang/FastMaskRCNN#98]
I did run make in libs before python train/train.py, but it still complains no module named 'nms'

(myVE35) wenzhen@instance-5:~/FastMaskRCNN/libs$ make
python setup.py build_ext --inplace
running build_ext
skipping 'boxes/bbox.c' Cython extension (up-to-date)
skipping 'boxes/cython_anchor.c' Cython extension (up-to-date)
skipping 'boxes/cython_bbox_transform.c' Cython extension (up-to-date)
skipping 'boxes/nms.c' Cython extension (up-to-date)
skipping 'nms/cpu_nms.c' Cython extension (up-to-date)
skipping 'nms/gpu_nms.cpp' Cython extension (up-to-date)
rm -rf build
sh make.sh
make[1]: Entering directory '/home/wenzhen/FastMaskRCNN/libs/datasets/pycocotools'
python setup.py build_ext --inplace
running build_ext
rm -rf build
make[1]: Leaving directory '/home/wenzhen/FastMaskRCNN/libs/datasets/pycocotools'
/home/wenzhen/FastMaskRCNN/libs
(myVE35) wenzhen@instance-5:~/FastMaskRCNN/libs$ cd ..
(myVE35) wenzhen@instance-5:~/FastMaskRCNN$ python train/train.py
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "train/train.py", line 21, in <module>
    import libs.nets.pyramid_network as pyramid_network
  File "train/../libs/nets/pyramid_network.py", line 9, in <module>
    from libs.boxes.roi import roi_cropping
  File "train/../libs/boxes/__init__.py", line 9, in <module>
    import nms
ImportError: No module named 'nms'

**Comment by zhuwenzhen** [comment]
I fixed it by changing train/../libs/boxes/__init__.py import directories.

**Comment by kylemin** [comment]
Could you explain more about this? I haven't resolved this problem yet..

**Comment by zhuwenzhen** [comment]
You need to fix this file: libs/boxes/__init__.py
https://github.com/zhuwenzhen/FastMaskRCNN/commit/09f51e968f170e442e8cf20cf88315d12ffb3315

**Comment by maxlchina** [comment]
i fixed it by changing train/../libs/boxes/init.py from . import nms
