### ISSUE TITLE
Mask looks very wrong

### ISSUE THREAD

**Issue by zhuwenzhen** [CharlesShang/FastMaskRCNN#99]
I trained > 100k, the loss looks fine, bounding box looks ok, but the mask looks very wrong. Is it the visualization bug or we need more training?

<img width="557" alt="screenshot 2017-07-02 15 55 46" src="https://user-images.githubusercontent.com/6295544/27773067-7254ac8c-5f3f-11e7-9a9e-659fcd960727.png">
<img width="485" alt="screenshot 2017-07-02 15 55 54" src="https://user-images.githubusercontent.com/6295544/27773068-7406012a-5f3f-11e7-9e5e-218e37671741.png">
<img width="469" alt="screenshot 2017-07-02 15 56 00" src="https://user-images.githubusercontent.com/6295544/27773071-79678f6c-5f3f-11e7-9421-1f8276bb5b4b.png">
<img width="384" alt="screenshot 2017-07-02 15 57 39" src="https://user-images.githubusercontent.com/6295544/27773073-7b92eee4-5f3f-11e7-9aea-5956fec12885.png">
<img width="389" alt="screenshot 2017-07-02 15 57 47" src="https://user-images.githubusercontent.com/6295544/27773074-7d7c53f8-5f3f-11e7-9a11-9d3e22beb7a5.png">
<img width="382" alt="screenshot 2017-07-02 15 57 54" src="https://user-images.githubusercontent.com/6295544/27773075-7f8cc8b2-5f3f-11e7-92d2-ce5f59db343c.png">

**Comment by Cangrc** [comment]
Masks have to be in the form of 0s and 1s, something is problematic with the mask code. I also obtained very similar results.

**Comment by HuangBo-Terraloupe** [comment]
Can you share the evaluation code? how to visualize the masks and bounding boxes.

**Comment by insikk** [comment]
It seem like pred_mask has some random values.

**Comment by Cangrc** [comment]
Can someone @zhuwenzhen @souryuu @realwecan manage to correct above predicted mask? Thanks

**Comment by astromme** [comment]
I also see this. Looking at the code, I see:

From https://github.com/CharlesShang/FastMaskRCNN/blob/a70dcdbb16b75f145cba4a5eda92400935ab863b/libs/nets/pyramid_network.py#L344
```
        ## mask head
        m = cropped_rois
        for _ in range(4):
            m = slim.conv2d(m, 256, [3, 3], stride=1, padding='SAME', activation_fn=tf.nn.relu)
        # to 28 x 28
        m = slim.conv2d_transpose(m, 256, 2, stride=2, padding='VALID', activation_fn=tf.nn.relu)
        tf.add_to_collection('__TRANSPOSED__', m)
        m = slim.conv2d(m, num_classes, [1, 1], stride=1, padding='VALID', activation_fn=None)
          
        # add a mask, given the predicted boxes and classes
        outputs['mask'] = {'mask':m, 'cls': classes, 'score': scores}
```

From https://github.com/CharlesShang/FastMaskRCNN/blob/a70dcdbb16b75f145cba4a5eda92400935ab863b/libs/nets/pyramid_network.py#L606
```
    # final network visualization
    first_mask = outputs['mask']['mask'][:1]
    first_mask = tf.transpose(first_mask, [3, 1, 2, 0])

    visualize_final_predictions(outputs['final_boxes']["box"], end_points["input"], first_mask)
```

From https://github.com/CharlesShang/FastMaskRCNN/blob/a70dcdbb16b75f145cba4a5eda92400935ab863b/libs/visualization/summary_utils.py#L37
```
def visualize_final_predictions(boxes, image, masks):
    visualize_masks(masks, "pred_mask")
    visualize_bb(image, boxes, "final_bb_pred")
```

Seems like there isn't a sigmoid. I'm not exactly sure how to add it though.

**Comment by Tetsujinfr** [comment]
Did anyone found a solution to fix the above on mask accuracy?
thanks
Tets

**Comment by souryuu** [comment]
I thought tf.sigmoid(outputs['mask']['mask']) should do a fine work. However, it did not work when I tried to visualize masks on tensorboard. So I wrote another visualization function using PIL to create .png. It works fine for drawing predicted masks on images during training. If you are interested, you can look at my visualization fork. However, I changed a lot of things in that fork and the code is totally mess.

**Comment by lengly** [comment]
Thanks @souryuu , I try your code and it works fine. 
BTW, you really change a lot  :-)

**Comment by realwecan** [comment]
@lengly Just wondering if you were able to reproduce any experimental evaluation results from the paper (or obtaining a close performance)? Thanks!

**Comment by lengly** [comment]
@realwecan You can try souryuu's code, it'll save some images which make sense. I only try 60k iter. So the result isn't as good as the paper.

**Comment by Cangrc** [comment]
@souryuu Your fork is truly beneficial thank you very much for your efforts. However I didn't understand why test.py and train.py differ that much by just looking at the code, could you please explain it? Images created by test.py predicts only human labels even they are not humans sometimes. On the contrary, images created by train.py involve various types of labels but with intensive number of bounding box compared to test.py.
![sooryuquestion](https://user-images.githubusercontent.com/11715361/29147739-3a8fc546-7d69-11e7-9138-57fccf27d2dc.jpg)

**Comment by lengly** [comment]
@Cangrc Hi, does your test.py work without any modification? I run train.py for 50k iter. and when I run test.py, there is no mask or bbox. 
Also, please see [here](https://github.com/CharlesShang/FastMaskRCNN/pull/96), souryuu said during the first 50k iter, the result biased to person class. But after 600k iter, it works fine.

**Comment by Cangrc** [comment]
Yes it works without any modification. I think I am somewhere near 200k iteration.

**Comment by souryuu** [comment]
If you use the code in my fork without any modification, your batch normalization should not be properly trained up until now because update_bn in config_v1.py was set to False. Change that to True and train the network again. During test, set all is_training flag in test.py to False. You should see significant improvement.

**Comment by realwecan** [comment]
@souryuu Thanks heaps! Just wanted to clarify here, in your latest code you have added the IS_TRAINING flag. I can see that when IS_TRAINING==True, update_bn will be set to True (and False otherwise). Am I correct to assume that I can just use this version of code as is, as long as I set IS_TRAINING=True when training, and IS_TRAINING=False during test?

**Comment by souryuu** [comment]
@realwecan Yes it should be something like that. However, in the latest version on "fix_testing" branch, all "is_training" in train.py and test.py are already set to True and False respectively. BN should work fine without any setting.

**Comment by realwecan** [comment]
@souryuu Thanks for your prompt reply! Just wondering if you have ever encountered a problem where you see the regular_loss constantly rising. Could this caused by improper settings of the learning rate and the loss weights? I have been experiencing this in a few versions of the code.

**Comment by souryuu** [comment]
@realwecan Yes I encountered that in the early stage of training. Afterward, it gradually reduced.
Setting learning rate and loss weight too high should temporary increase the regular loss. However, I am not sure if it matters. From what I understand,. It is just a loss from a regularization term that helps you not overfitting to the training data.

**Comment by realwecan** [comment]
@souryuu When testing with the latest code in the fix_testing branch I met the following error:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/script_ops.py", line 82, in __call__
    ret = func(*args)
  File "/home/twang/work/segmentation/baselines/FastMaskRCNN/train/../libs/layers/sample.py", line 127, in sample_rpn_outputs_wrt_gt_boxes
    gt_argmax_overlaps = overlaps.argmax(axis=0) # G
ValueError: attempt to get argmax of an empty sequence

This error does not seem to exist in the code in your master branch. Do you have any idea what this might be coming from? Thanks!

**Comment by lengly** [comment]
@souryuu I try your latest code in master branch. I set is_training=True and train it for 60k iterations. When I set is_training=False, and run test.py, there're still no bbox & mask. Why? Is it because my iteration is not enough?

**Comment by souryuu** [comment]
@realwecan in pyramid_networks line 272, setting only_positive flag in sample_rpn_outputs to False should solve your issue. It is the flag to filter rois with RPN's confidence value < 0.5 for speed up the training. Since at the beginning of training RPN can not provide reliable confidence value, this should be turned off.

@lengy Can you see masks and bounding boxs in images created during training ?

**Comment by lengly** [comment]
@souryuu Yes, when training, it works fine. the box & mask in training image are just like Cangrc's result above.

**Comment by souryuu** [comment]
@lengly Check if update_bn in config_v1.py is set to True during training. If not, set it to True and train the network again.

**Comment by lengly** [comment]
@souryuu Yeah, update_bn is true when training. I use your latest code in master branch, and the only change is per_process_gpu_memory_fraction=0.95, but I think it should not affect result.  Did the latest master branch test.py work fine in your side?

**Comment by souryuu** [comment]
It works fine for me. During training, did "target" and "predicted" match ? 
If no, I think your RCNN did not learn well. you can keep RPN and begin training RCNN and mask network by commenting out line 76 and uncomment line 80-125 in train.py.
If yes, I recommend you to use the code in fix_testing branch instead. However, you need to retrain the network again since the anchors in both branches do not match.

**Comment by lengly** [comment]
@souryuu Yeah they're nearly match.  I'll try fix_testing branch. I really appreciate for your help!

**Comment by Cangrc** [comment]
@souryuu fix_testing branch is being trained 3 or 4 times slower than the previous ones what might be the reason for that? Thank you very much for allocating time

**Comment by gengyixuan** [comment]
@Cangrc @realwecan @lengly It would be greatly appreciated if some of you could maybe share the trained weights. It would take a long time for my computer to reach 600k iterations. Thanks!

**Comment by Yc174** [comment]
Can you share the trained weights?Thanks very much!! @souryuu @gengyixuan @lengly @realwecan

**Comment by Sutong1115** [comment]
@souryuu  When I run train.py for 300k iter, the result looks bad, target and predict do not match. What should I do? commenting out line 76 and uncomment line 80-125 in train.py? And then training the code again?

**Comment by Sutong1115** [comment]
@souryuu  I set is_training=True and train it for 300k iterations. When I set is_training=False, and run test.py, the result looks bad, target and predict do not match. What should I do? commenting out line 76 and uncomment line 80-125 in train.py? And then training the code again?

**Comment by trminh89** [comment]
I trained until 400K but the prediction looks very bad. Anyone succeed?
Btw, t=it seems we have a new extended version of Mask RCNN on Caffe [AffordanceNet](https://github.com/nqanh/affordance-net). The result looks interesting to me.

**Comment by Yiman-GO** [comment]
@souryuu Thanks for your code! I tried your code following the 'README.md' but error happened.
 It said:"IOError: [Errno 2] No such file or directory: './output/mask_rcnn/est_imgs/train_est_0.jpg'
"
From train.py I could not see any code about how to generate file 'est_imgs'. So can you tell me if i missed some steps about it? 
I will appreciate it.
